 "use client";

import { useEffect, useState } from "react";

export default function SuscripcionPage() {
  const [data,setData]=useState<any>(null); const [plans,setPlans]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState("");
  useEffect(()=>{Promise.all([fetch("/api/subscription").then(r=>r.json()),fetch("/api/plans").then(r=>r.json())]).then(([s,p])=>{setData(s);setPlans(p.plans||[])}).finally(()=>setLoading(false))},[]);
  async function change(code:string){setMsg("Actualizando plan…"); const r=await fetch("/api/subscription",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planCode:code,billingInterval:"MONTHLY"})}); const j=await r.json(); if(r.ok){setData(j);setMsg("Plan actualizado. La conexión de cobro recurrente se completará en la etapa de facturación.")}else setMsg(j.error||"No fue posible actualizar");}
  if(loading)return <main className="page">Cargando…</main>;
  return <main className="page"><a href="/dashboard">← Dashboard</a><h1>Mi suscripción</h1>{data&&<div className="hero"><div><span className="muted">Plan actual</span><h2>{data.plan.name}</h2><p>{data.status==="TRIALING" ? `Prueba gratuita hasta ${new Date(data.trialEndAt).toLocaleDateString("es-CL")}` : `Estado: ${data.status}`}</p></div><div className="trial">🎁 30 días gratis</div></div>}<h2>Planes</h2><div className="grid">{plans.filter(p=>p.code!=="FREE"&&p.code!=="ENTERPRISE").map(p=><div className="card" key={p.code}><h3>{p.name}</h3><strong>${Number(p.monthlyPrice).toLocaleString("es-CL")} / mes</strong><p>{p.description}</p><button onClick={()=>change(p.code)}>Elegir plan</button></div>)}</div>{msg&&<p className="msg">{msg}</p>}<style jsx>{`.page{max-width:1100px;margin:auto;padding:35px 20px;font-family:Arial;color:#17202a}.muted{color:#667085}.hero{display:flex;justify-content:space-between;align-items:center;border:1px solid #e4e7ec;border-radius:16px;padding:22px;margin:20px 0 35px}.trial{background:#f2f4f7;border-radius:10px;padding:12px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card{border:1px solid #e4e7ec;border-radius:14px;padding:20px}.card button{margin-top:15px;border:0;background:#111827;color:white;padding:10px 14px;border-radius:9px;cursor:pointer}.msg{background:#f2f4f7;padding:12px;border-radius:9px}@media(max-width:700px){.grid{grid-template-columns:1fr}.hero{display:block}}`}</style></main>;
}
